site_name: LightGraphs.jl
site_author: Carlo Lucibello
repo_url: https://github.com/CarloLucibello/SAT.jl/
docs_dir: 'build'

theme: readthedocs

pages:
  - 'Getting Started': 'index.md'
  - 'Formulas': 'formulas.md'
  - 'Solvers': 'solvers.md'

markdown_extensions:
  - extra
  - tables
  - fenced_code

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js
